<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\CustomModuleManager;

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Session;
use Illuminate\Support\Collection;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\CustomModuleManager\CustomModuleManager;
use Jefferson49\Webtrees\Module\CustomModuleManager\Factories\CustomModuleUpdateFactory;
use Jefferson49\Webtrees\Module\CustomModuleManager\ModuleUpdates\AbstractModuleUpdate;
use Jefferson49\Webtrees\Module\CustomModuleManager\ModuleUpdates\GithubModuleUpdate;
use Jefferson49\Webtrees\Module\CustomModuleManager\RequestHandlers\CustomModuleUpdatePage;
use Jefferson49\Webtrees\Module\CustomModuleManager\RequestHandlers\ModuleInformationModal;
use Jefferson49\Webtrees\Module\CustomModuleManager\RequestHandlers\ModuleUpgradeWizardPage;
use Jefferson49\Webtrees\Module\CustomModuleManager\Configuration\ModuleUpdateServiceConfiguration;


/**
 * @var string     $title
 * @var string     $cmm_title
 * @var bool       $cmm_update
 * @var bool       $runs_with_webtrees_version
 * @var bool       $php_extension_zip_missing
 * @var Collection $custom_modules
 * @var Collection $themes
 * @var array      $module_names
 * @var bool       $fetch_latest
 */

$module_service = New ModuleService();
/** @var CustomModuleManager $custom_module_manager To avoid IDE warnings */
$custom_module_manager = $module_service->findByName(CustomModuleManager::activeModuleName());
$modules_to_show = $custom_module_manager->getPreference(CustomModuleManager::PREF_MODULES_TO_SHOW, CustomModuleManager::PREF_SHOW_ALL);
$activated = CustomModuleManager::runsWithInstalledWebtreesVersion();

?>

<?= view('components/breadcrumbs', ['links' => [
    route(ControlPanel::class) => MoreI18N::xlate('Control panel'),
    $custom_module_manager->getConfigLink() => $custom_module_manager->title(),
    $title
    ]]) ?>

<h1><?= $title ?></h1>

<?= view(CustomModuleManager::viewsNamespace() . '::deactivated', [
        'runs_with_webtrees_version' => $runs_with_webtrees_version,
        'php_extension_zip_missing'  => $php_extension_zip_missing,
]) ?>

<?php if ($cmm_update) : ?>
    <div class="alert alert-warning" role="alert" style="white-space: pre-wrap;"><?= I18N::translate('A new version of "%s" is available. It is recommended to upgrade to the latest version before other custom modules are installed/upgraded.', $cmm_title) ?></div>
<?php endif ?>

<?= I18N::translate('Typically, custom modules versions are updated every 24 hours. You can check if later versions are available.') ?><?= view('icons/spacer') ?></div><a href="<?= e(route(CustomModuleUpdatePage::class, [
        'fetch_latest' => true,
    ])) ?>" type="submit" class="btn btn-primary">
    <?= MoreI18N::xlate('check now') ?>
</a>
<div class="row mb-3"><?= view('icons/spacer') ?></div>

<table
    class="table table-bordered table-sm wt-table-module-updates datatables d-none"
    <?= view('lists/datatables-attributes') ?>
    data-columns="<?= e(json_encode([
        ['type' => 'html'],
        ['type' => 'html'],
        null,
        null,
        null,
        null,
        null,
        ['searchable' => false],
        ['type' => 'html', 'searchable' => false],
    ], JSON_THROW_ON_ERROR)) ?>"
>
    <caption class="visually-hidden">
        <?= $caption ?? I18N::translate('Module Updates') ?>
    </caption>

    <thead>
        <tr>
            <th><?= MoreI18N::xlate('Title') ?></th>
            <th><?= MoreI18N::xlate('Description') ?></th>
            <th><?= I18N::translate('Folder (within modules_v4)') ?></th>
            <th><?= MoreI18N::xlate('Category') ?></th>
            <th><?= I18N::translate('Current Version') ?></th>
            <th><?= I18N::translate('Latest Version') ?></th>
            <th><?= I18N::translate('Update Service') ?></th>
            <th><?= MoreI18N::xlate('Status') ?></th>
            <th><?= MoreI18N::xlate('Action') ?></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($module_names as $module_name => $standard_module_name) : ?>
            <?php $module = $module_service->findByName($module_name, true) ?>
            <?php if ($module === null) : ?>
                <?php if ($modules_to_show === CustomModuleManager::PREF_SHOW_INSTALLED) : ?><?php continue ?><?php endif ?>			
                <?php $module_status = I18N::translate('not installed') ?>
            <?php else : ?>
                <?php if ($modules_to_show === CustomModuleManager::PREF_SHOW_NOT_INSTALLED) : ?><?php continue ?><?php endif ?>						
                <?php if ($module->isEnabled()) : ?>
                    <?php $module_status = I18N::translate('enabled') ?>
                <?php else : ?>
                    <?php $module_status = I18N::translate('disabled') ?>
                <?php endif ?>						
            <?php endif ?>						
            <?php $current_language = Session::get('language', '') ?>
            <?php $update_service_available = ModuleUpdateServiceConfiguration::getUpdateServiceName($module_name) !== '' ?>
            <?php $module_update_service = CustomModuleUpdateFactory::make($module_name) ?>
            <?php if ($update_service_available) : ?>
                <?php $module_update_service_name = $module_update_service->name() ?>
                <?php $module_title = $module_update_service->title($current_language) ?>
                <?php /** @var GithubModuleUpdate $module_update_service To avoid IDE warnings */ ?>
                <?php $default_module_title = $module_update_service->title() ?>
                <?php $module_description = $module_update_service->description($current_language) ?>
                <?php $default_module_description = $module_update_service->description() ?>
                <?php $is_theme = $module_update_service->moduleIsTheme() ?>
                <?php $category = $module_update_service->getCategory() ?>
                <?php $current_version = $module_update_service->customModuleVersion() ?>
                <?php $latest_version = $module_update_service->customModuleLatestVersion($fetch_latest) ?>
                <?php $latest_version = $latest_version !== '' ? $latest_version : I18N::translate('not received') ?>
                <?php $documentation_url = $module_update_service->documentationUrl() ?>
            <?php else : ?>
                <?php $module_update_service_name = I18N::translate('not available') ?>
                <?php $module_title = $module->title() ?>
                <?php $module_description = $module->description() ?>
                <?php I18N::init(CustomModuleManager::DEFAULT_LANGUAGE) ?>
                <?php Session::put('language', CustomModuleManager::DEFAULT_LANGUAGE) ?>
                <?php $default_module_title = $module->title() ?>
                <?php $default_module_description = $module->description() ?>
                <?php I18N::init($current_language) ?>
                <?php Session::put('language', $current_language) ?>
                <?php $default_module_title = $module_title ?>
                <?php $default_module_description = $module_description ?>
                <?php $is_theme = $themes->contains($module) ?>
                <?php $category = $is_theme ? ModuleUpdateServiceConfiguration::CATEGORY_THEME : '' ?>
                <?php /** @var CustomModuleManager $module To avoid IDE warnings */ ?>
                <?php $current_version = $module->customModuleVersion() ?>
                <?php $latest_version = $module->customModuleLatestVersion() ?>
                <?php $documentation_url = '' ?>
            <?php endif ?>	
            <?php if (CustomModuleManager::versionCompare($latest_version, $current_version) < 0) : ?>
                <?php $latest_version = $current_version ?>
            <?php endif ?>
            <?php if ($module !== null) : ?>
                <?php $current_version = $current_version !== '' ? $current_version : I18N::translate('not received') ?>
            <?php endif ?>				
            <?php $installation_folder = AbstractModuleUpdate::getInstallationFolderFromModuleName($module_name) ?>
            <?php $show_default_description = ($module_description === '' OR $module_description === $default_module_description) && strpos($current_language, 'en', 0) === false ?>
            <?php if ($module_title === '') : ?>
                <?php $module_title = $default_module_title ?>
            <?php endif ?>				
            <?php if ($show_default_description) : ?>
                <?php $module_description = $default_module_description ?>
            <?php endif ?>
            <?php $module_title_sort = str_replace(["\u26b6 ", "\u210d ", "\u210d&\u210dwt ", '⚶ ', 'ℍ ', 'ℍ&ℍwt ', ], '', $module_title) ?>

            <tr>
                <!-- Title -->
                <td data-sort="<?= e($module_title_sort) ?>">
                <a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route(ModuleInformationModal::class, [
                        'module_name'                => $module_name,
                        'module'                     => $module,
                        'module_update_service'      => $module_update_service,
                        'module_update_service_name' => $module_update_service_name,
                        'module_title'               => $module_title,
                        'module_description'         => $module_description,
                        'show_default_description'   => $show_default_description,
                        'module_status'              => $module_status,
                        'is_theme'                   => $is_theme,
                        'category'                   => $category,
                        'current_version'            => $current_version,
                        'latest_version'             => $latest_version,
                        'installation_folder'        => $installation_folder,
                        'documentation_url'          => $documentation_url,
                    ])) ?>">
                    <?= e($module_title) ?>
                </a>
                </td>

                <!-- Description -->
                <td data-sort="<?= e($module_description) ?>">
                    <?php if ($show_default_description) : ?>
                        <?= CustomModuleManager::DEFAULT_LANGUAGE_PREFIX ?><br>
                    <?php endif ?>
                    <?= e($module_description) ?>
                </td>

                <!-- Folder -->
                <td data-sort="<?= e($installation_folder) ?>">
                    <?= e($installation_folder) ?>
                </td>

                <!--Category -->
                <td class="text-center" data-sort="<?= e($category) ?>">
                    <?= e($category) ?>
                </td>

                <!-- Current version -->
                <td data-sort="<?= e(CustomModuleManager::normalizeVersion($current_version)) ?>">
                    <?= e(CustomModuleManager::normalizeVersion($current_version)) ?>
                </td>

                <!-- Latest version -->
                <td data-sort="<?= e(CustomModuleManager::normalizeVersion($latest_version)) ?>">
                    <?= e(CustomModuleManager::normalizeVersion($latest_version)) ?>
                </td>

                <!--Update Service -->
                <td class="text-center" data-sort="<?= $module_update_service_name ?>">
                    <?= $module_update_service_name ?>
                </td>

                <!-- Status -->
                <td data-sort="<?= $module_status ?>">
                    <?= $module_status ?>
                </td>

                <!--Action -->
                <?php $action = '' ?>
                <?php $action_label = '' ?>
                <?php if ($module !== null && CustomModuleManager::versionCompare($latest_version, $current_version) > 0) : ?>
                    <?php $action = CustomModuleManager::ACTION_UPDATE ?>
                    <?php $action_label = I18N::translate('Update module') ?>
                <?php elseif ($module_status === I18N::translate('not installed')) : ?>
                    <?php $action = CustomModuleManager::ACTION_INSTALL ?>
                    <?php $action_label = I18N::translate('Install module') ?>
                <?php endif ?>						
                <td data-sort="<?= $action_label ?>">
                    <?php if ($action_label !== '' && $update_service_available) : ?>
                        <a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route(ModuleUpgradeWizardPage::class, [
                                'module_name'     => $module_name,
                                'current_version' => $current_version,
                                'latest_version'  => $latest_version,
                                'action'          => $action,
                                'modal'           => true,
                            ])) ?>" type="submit" class="btn btn-<?= $action === CustomModuleManager::ACTION_UPDATE ? 'primary' : 'secondary' ?>">
                            <?= $action_label ?>
                        </a>
                    <?php endif ?>						
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>

<?= view('modals/ajax') ?>
