<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\CustomModuleManager;

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Session;
use Illuminate\Support\Collection;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\CustomModuleManager\CustomModuleManager;
use Jefferson49\Webtrees\Module\CustomModuleManager\Factories\CustomModuleUpdateFactory;
use Jefferson49\Webtrees\Module\CustomModuleManager\ModuleUpdates\AbstractModuleUpdate;
use Jefferson49\Webtrees\Module\CustomModuleManager\ModuleUpdates\GithubModuleUpdate;
use Jefferson49\Webtrees\Module\CustomModuleManager\RequestHandlers\CustomModuleUpdatePage;
use Jefferson49\Webtrees\Module\CustomModuleManager\RequestHandlers\ModuleInformationModal;
use Jefferson49\Webtrees\Module\CustomModuleManager\RequestHandlers\ModuleUpgradeWizardPage;
use Jefferson49\Webtrees\Module\CustomModuleManager\Configuration\ModuleUpdateServiceConfiguration;
use Jefferson49\Webtrees\Module\CustomModuleManager\RequestHandlers\CustomModuleActivateAction;
use Jefferson49\Webtrees\Module\CustomModuleManager\RequestHandlers\ReleaseNotesModal;


/**
 * @var string              $title
 * @var CustomModuleManager $custom_module_manager
 * @var ModuleService       $module_service
 * @var Collection          $custom_modules
 * @var Collection          $themes
 * @var array               $module_names
 * @var bool                $fetch_latest
 * @var string              $modules_to_show
 */

?>

<?= view('components/breadcrumbs', ['links' => [
    route(ControlPanel::class) => MoreI18N::xlate('Control panel'),
    $custom_module_manager->getConfigLink() => $custom_module_manager->title(),
    $title
    ]]) ?>

<h1><?= $title ?></h1>

<?= view(CustomModuleManager::viewsNamespace() . '::deactivated', [
        'runs_with_webtrees_version' => CustomModuleManager::runsWithInstalledWebtreesVersion(),
        'php_extension_zip_missing'  => !extension_loaded('zip'),
]) ?>

<?php if ($custom_module_manager->isLowerThanLatestVersion()) : ?>
    <div class="alert alert-warning" role="alert" style="white-space: pre-wrap;"><?= I18N::translate('A new version of "%s" is available. It is recommended to upgrade to the latest version before other custom modules are installed/upgraded.', $custom_module_manager->title()) ?></div>
<?php endif ?>

<?= I18N::translate('Typically, custom modules versions are updated every 24 hours. You can check if later versions are available.') ?><?= view('icons/spacer') ?></div><a href="<?= e(route(CustomModuleUpdatePage::class, [
        'fetch_latest' => true,
    ])) ?>" type="submit" class="btn btn-primary">
    <?= MoreI18N::xlate('check now') ?>
</a>
<div class="row mb-3"><?= view('icons/spacer') ?></div>


<form method="post" action="<?= e(route(CustomModuleActivateAction::class)) ?>">
    <table
        class="table table-bordered table-sm wt-table-module-updates datatables d-none"
        <?= view('lists/datatables-attributes') ?>
        data-columns="<?= e(json_encode([
            ['type' => 'html'],
            ['type' => 'html'],
            null,
            null,
            null,
            null,
            null,
            ['searchable' => false],
            ['type' => 'html', 'searchable' => false],
            ['type' => 'html', 'searchable' => false],
        ], JSON_THROW_ON_ERROR)) ?>"
    >
        <caption class="visually-hidden">
            <?= $caption ?? I18N::translate('Module Updates') ?>
        </caption>

        <thead>
            <tr>
                <th><?= MoreI18N::xlate('Title') ?></th>
                <th><?= MoreI18N::xlate('Description') ?></th>
                <th><?= I18N::translate('Folder (within modules_v4)') ?></th>
                <th><?= MoreI18N::xlate('Category') ?></th>
                <th><?= I18N::translate('Current Version') ?></th>
                <th><?= I18N::translate('Latest Version') ?></th>
                <th><?= I18N::translate('Update Service') ?></th>
                <th><?= MoreI18N::xlate('Enabled') ?></th>
                <th><?= I18N::translate('Install') ?></th>
                <th><?= MoreI18N::xlate('Delete') ?></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($module_names as $module_name => $standard_module_name) : ?>
                <?php $module = $module_service->findByName($module_name, true) ?>
                <?php if ($module === null) : ?>
                    <?php if ($modules_to_show === CustomModuleManager::PREF_SHOW_INSTALLED) : ?><?php continue ?><?php endif ?>	
                    <?php $module_status = I18N::translate('not installed') ?>
                <?php else : ?>
                    <?php if ($modules_to_show === CustomModuleManager::PREF_SHOW_NOT_INSTALLED) : ?><?php continue ?><?php endif ?>						
                    <?php if ($module->isEnabled()) : ?>
                        <?php $module_status = '1' ?>
                    <?php else : ?>
                        <?php $module_status = '0' ?>
                    <?php endif ?>						
                <?php endif ?>						
                <?php $current_language = Session::get('language', '') ?>
                <?php $update_service_available = ModuleUpdateServiceConfiguration::getUpdateServiceName($module_name) !== '' ?>
                <?php $module_update_service = CustomModuleUpdateFactory::make($module_name) ?>
                <?php if ($update_service_available) : ?>
                    <?php $module_update_service_name = $module_update_service->name() ?>
                    <?php $module_title = $module_update_service->title($current_language) ?>
                    <?php /** @var GithubModuleUpdate $module_update_service To avoid IDE warnings */ ?>
                    <?php $default_module_title = $module_update_service->title() ?>
                    <?php $module_description = $module_update_service->description($current_language) ?>
                    <?php $default_module_description = $module_update_service->description() ?>
                    <?php $is_theme = $module_update_service->moduleIsTheme() ?>
                    <?php $category = $module_update_service->getCategory() ?>
                    <?php $current_version = $module_update_service->customModuleVersion() ?>
                    <?php if ($module !== null) : ?>
                        <?php $latest_version = $module_update_service->customModuleLatestVersion($fetch_latest) ?>
                    <?php else : ?>
                        <?php $latest_version = '' ?>
                        <?php $later_version_available = false ?>
                    <?php endif ?>
                    <?php $documentation_url = $module_update_service->documentationUrl() ?>
                <?php else : ?>
                    <?php $module_update_service_name = I18N::translate('not available') ?>
                    <?php $module_title = $module->title() ?>
                    <?php $module_description = $module->description() ?>
                    <?php $default_module_title = $module_title ?>
                    <?php $default_module_description = $module_description ?>
                    <?php $is_theme = $themes->contains($module) ?>
                    <?php $category = $is_theme ? ModuleUpdateServiceConfiguration::CATEGORY_THEME : '' ?>
                    <?php /** @var CustomModuleManager $module To avoid IDE warnings */ ?>
                    <?php $current_version = $module->customModuleVersion() ?>
                    <?php $latest_version = $module->customModuleLatestVersion() ?>
                    <?php $documentation_url = '' ?>
                <?php endif ?>
                <?php if ($module !== null) : ?>
                    <?php $current_version = $current_version !== '' ? $current_version : I18N::translate('not available') ?>
                    <?php $latest_version = $latest_version !== '' ? $latest_version : I18N::translate('not available') ?>
                <?php endif ?>
                <?php if (CustomModuleManager::versionCompare($module_name, $latest_version, $current_version) > 0) : ?>
                    <?php $later_version_available = true ?>
                <?php else : ?>
                    <?php $later_version_available = false ?>
                <?php endif ?>
                <?php $installation_folder = AbstractModuleUpdate::getInstallationFolderFromModuleName($module_name) ?>
                <?php $show_default_description = ($module_description === '' OR $module_description === $default_module_description) && strpos($current_language, 'en', 0) === false ?>
                <?php if ($module_title === '') : ?>
                    <?php $module_title = $default_module_title ?>
                <?php endif ?>				
                <?php if ($show_default_description) : ?>
                    <?php $module_description = $default_module_description ?>
                <?php endif ?>
                <?php $module_title_sort = str_replace(["\u26b6 ", "\u210d ", "\u210d&\u210dwt ", '⚶ ', 'ℍ ', 'ℍ&ℍwt ', ], '', $module_title) ?>

                <tr>
                    <!-- Title -->
                    <td data-sort="<?= e($module_title_sort) ?>">
                    <a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route(ModuleInformationModal::class, [
                            'module_name'                => $module_name,
                            'module'                     => $module,
                            'module_update_service'      => $module_update_service,
                            'module_update_service_name' => $module_update_service_name,
                            'module_title'               => $module_title,
                            'module_description'         => $module_description,
                            'show_default_description'   => $show_default_description,
                            'module_status'              => $module_status,
                            'is_theme'                   => $is_theme,
                            'category'                   => $category,
                            'current_version'            => $current_version,
                            'latest_version'             => $latest_version,
                            'installation_folder'        => $installation_folder,
                            'documentation_url'          => $documentation_url,
                        ])) ?>">
                        <?= e($module_title) ?>
                    </a>
                    </td>

                    <!-- Description -->
                    <td data-sort="<?= e($module_description) ?>">
                        <?php if ($show_default_description) : ?>
                            <?= CustomModuleManager::DEFAULT_LANGUAGE_PREFIX ?><br>
                        <?php endif ?>
                        <?= e($module_description) ?>
                    </td>

                    <!-- Folder -->
                    <td data-sort="<?= e($installation_folder) ?>">
                        <?= e($installation_folder) ?>
                    </td>

                    <!--Category -->
                    <td class="text-center" data-sort="<?= e($category) ?>">
                        <?= e($category) ?>
                    </td>

                    <!-- Current version -->
                    <td data-sort="<?= e(CustomModuleManager::normalizeVersion($module_name, $current_version)) ?>">
                        <?= e(CustomModuleManager::normalizeVersion($module_name, $current_version)) ?>
                    </td>

                    <!-- Latest version -->
                    <td data-sort="<?= e(CustomModuleManager::normalizeVersion($module_name, $latest_version)) ?>">
                        <?php if ( $later_version_available && $current_version !== '' && $module_update_service_name === GithubModuleUpdate::NAME && $module_update_service->providesGithubReleases()) : ?>
                            <a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route(ReleaseNotesModal::class, [
                                    'module_name'                => $module_name,
                                    'module_title'               => $module_title,
                                    'latest_version'             => $latest_version,
                                ])) ?>" type="submit" class="btn btn-primary">
                                <?= e(CustomModuleManager::normalizeVersion($module_name, $latest_version)) ?>
                            </a>
                        <?php else : ?>
                            <?= e(CustomModuleManager::normalizeVersion($module_name, $latest_version)) ?>
                        <?php endif ?>						
                    </td>

                    <!--Update Service -->
                    <td class="text-center" data-sort="<?= $module_update_service_name ?>">
                        <?= $module_update_service_name ?>
                    </td>

                    <!-- Enabled -->
                    <td data-sort="<?= $module_status ?>">
                        <?php if ($module !== null) : ?>
                            <?= view('components/checkbox', ['label' => '', 'name' => 'status-' . $module->name(), 'checked' => $module->isEnabled()]) ?>
                        <?php else : ?>
                            <?= $module_status ?>
                        <?php endif ?>
                    </td>

                    <!--Install -->
                    <?php $action = '' ?>
                    <?php $action_label = '' ?>
                    <?php if ($module !== null && $later_version_available) : ?>
                        <?php $action = CustomModuleManager::ACTION_UPDATE ?>
                        <?php $action_label = I18N::translate('Update module') ?>
                    <?php elseif ($module_status === I18N::translate('not installed')) : ?>
                        <?php $action = CustomModuleManager::ACTION_INSTALL ?>
                        <?php $action_label = I18N::translate('Install module') ?>
                    <?php endif ?>						
                    <td data-sort="<?= $action_label ?>">
                        <?php if ($action_label !== '' && $update_service_available) : ?>
                            <a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route(ModuleUpgradeWizardPage::class, [
                                    'module_name'     => $module_name,
                                    'current_version' => $current_version,
                                    'latest_version'  => $latest_version,
                                    'action'          => $action,
                                ])) ?>" type="submit" class="btn btn-<?= $action === CustomModuleManager::ACTION_UPDATE ? 'primary' : 'secondary' ?>">
                                <?= $action_label ?>
                            </a>
                        <?php endif ?>						
                    </td>

                    <!--Delete -->
                    <?php $label = '' ?>
                    <?php if ($module !== null) : ?>
                        <?php $label = I18N::translate('Delete module') ?>
                    <?php endif ?>						
                    <td data-sort="<?= $label ?>">
                        <?php if ($module !== null) : ?>
                            <a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route(ModuleUpgradeWizardPage::class, [
                                    'module_name'     => $module_name,
                                    'action'          => CustomModuleManager::ACTION_DELETE,
                                ])) ?>" type="submit" class="btn btn-secondary">
                                <?= $label ?>
                            </a>
                        <?php endif ?>						
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>

    <div class="row mb-3"><?= view('icons/spacer') ?></div>  

    <button class="btn btn-primary" type="submit">
        <?= view('icons/save') ?>
        <?= MoreI18N::xlate('save') ?>
    </button>

    <br>
    <?= I18N::translate('Press the save button to enable/disable modules according to the checkbox in the "enabled" column.') ?>

    <?= csrf_field() ?>
</form>

<?= view('modals/ajax') ?>
