<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Module\ModuleAnalyticsInterface;
use Fisharebest\Webtrees\Module\ModuleBlockInterface;
use Fisharebest\Webtrees\Module\ModuleChartInterface;
use Fisharebest\Webtrees\Module\ModuleCustomInterface;
use Fisharebest\Webtrees\Module\ModuleDataFixInterface;
use Fisharebest\Webtrees\Module\ModuleFooterInterface;
use Fisharebest\Webtrees\Module\ModuleHistoricEventsInterface;
use Fisharebest\Webtrees\Module\ModuleLanguageInterface;
use Fisharebest\Webtrees\Module\ModuleListInterface;
use Fisharebest\Webtrees\Module\ModuleMenuInterface;
use Fisharebest\Webtrees\Module\ModuleReportInterface;
use Fisharebest\Webtrees\Module\ModuleSidebarInterface;
use Fisharebest\Webtrees\Module\ModuleTabInterface;
use Fisharebest\Webtrees\Module\ModuleThemeInterface;
use Jefferson49\Webtrees\Internationalization\MoreI18N;


/**
 * Code from: /resources/views/admin/modules.phmtl
 * 
 * @var ModuleCustomInterface       $module,
 */

?>

<table class="table table-bordered table-hover table-sm table-module-administration"
    <?= view('lists/datatables-attributes') ?>
    data-info="false"
    data-paging="false"
    data-filter="false"
>
    <caption class="visually-hidden">
        <?= I18N::translate('Module Usage') ?>
    </caption>
    <thead>
        <tr>
            <th class="text-center" title="<?= MoreI18N::xlate('Menus') ?>">
                <?= view('icons/menu') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Menus') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Tabs') ?>">
                <?= view('icons/tab') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Tabs') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Sidebars') ?>">
                <?= view('icons/sidebar') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Sidebars') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Blocks') ?>">
                <?= view('icons/block') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Blocks') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Data fixes') ?>">
                <?= view('icons/data-fix') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Data fixes') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Charts') ?>">
                <?= view('icons/chart') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Charts') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Lists') ?>">
                <?= view('icons/list') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Lists') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Reports') ?>">
                <?= view('icons/report') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Reports') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Footers') ?>">
                <?= view('icons/footer') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Footers') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Tracking and analytics') ?>">
                <?= view('icons/analytics') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Tracking and analytics') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Historic events') ?>">
                <?= view('icons/history') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Historic events') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Themes') ?>">
                <?= view('icons/theme') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Themes') ?></span>
            </th>
            <th class="text-center" title="<?= MoreI18N::xlate('Languages') ?>">
                <?= view('icons/language') ?>
                <span class="visually-hidden"><?= MoreI18N::xlate('Languages') ?></span>
            </th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td class="text-center" title="<?= MoreI18N::xlate('Menu') ?>">
                <?php if ($module instanceof ModuleMenuInterface) : ?>
                    <?= view('icons/menu') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('Menu') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center" title="<?= MoreI18N::xlate('Tab') ?>">
                <?php if ($module instanceof ModuleTabInterface) : ?>
                    <?= view('icons/tab') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('Tab') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center" title="<?= MoreI18N::xlate('Sidebar') ?>">
                <?php if ($module instanceof ModuleSidebarInterface) : ?>
                    <?= view('icons/sidebar') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('Sidebar') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center">
                <?php if ($module instanceof ModuleBlockInterface) : ?>
                    <?php if ($module->isUserBlock()) : ?>
                        <span title="<?= MoreI18N::xlate('My page') ?>">
                            <?= view('icons/block-user') ?>
                        </span>
                        <span class="visually-hidden">
                            <?= MoreI18N::xlate('My page') ?>
                        </span>
                    <?php endif ?>

                    <?php if ($module->isTreeBlock()) : ?>
                        <span title="<?= MoreI18N::xlate('Home page') ?>">
                            <?= view('icons/block-tree') ?>
                        </span>
                        <span class="visually-hidden">
                            <?= MoreI18N::xlate('Home page') ?>
                        </span>
                    <?php endif ?>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center" title="<?= MoreI18N::xlate('Data fix') ?>">
                <?php if ($module instanceof ModuleDataFixInterface) : ?>
                    <?= view('icons/data-fix') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('Data fix') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center" title="<?= MoreI18N::xlate('Chart') ?>">
                <?php if ($module instanceof ModuleChartInterface) : ?>
                    <?= view('icons/chart') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('Chart') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center" title="<?= MoreI18N::xlate('List') ?>">
                <?php if ($module instanceof ModuleListInterface) : ?>
                    <?= view('icons/list') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('List') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center" title="<?= MoreI18N::xlate('Report') ?>">
                <?php if ($module instanceof ModuleReportInterface) : ?>
                    <?= view('icons/report') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('Report') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center" title="<?= MoreI18N::xlate('Footer') ?>">
                <?php if ($module instanceof ModuleFooterInterface) : ?>
                    <?= view('icons/footer') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('Footer') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center" title="<?= MoreI18N::xlate('Tracking and analytics') ?>">
                <?php if ($module instanceof ModuleAnalyticsInterface) : ?>
                    <?= view('icons/analytics') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('Tracking and analytics') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center" title="<?= MoreI18N::xlate('Historic events') ?>">
                <?php if ($module instanceof ModuleHistoricEventsInterface) : ?>
                    <?= view('icons/history') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('Historic events') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center" title="<?= MoreI18N::xlate('Theme') ?>">
                <?php if ($module instanceof ModuleThemeInterface) : ?>
                    <?= view('icons/theme') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('Theme') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
            <td class="text-center" title="<?= MoreI18N::xlate('Language') ?>">
                <?php if ($module instanceof ModuleLanguageInterface) : ?>
                    <?= view('icons/language') ?>
                    <span class="visually-hidden"><?= MoreI18N::xlate('Language') ?></span>
                <?php else : ?>
                    -
                <?php endif ?>
            </td>
        </tr>
    </tbody>
</table>
