<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Services\ModuleService;
use Illuminate\Support\Collection;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\CustomModuleManager\CustomModuleManager;
use Jefferson49\Webtrees\Module\CustomModuleManager\Factories\CustomModuleUpdateFactory;
use Jefferson49\Webtrees\Module\CustomModuleManager\ModuleUpdates\AbstractModuleUpdate;
use Jefferson49\Webtrees\Module\CustomModuleManager\RequestHandlers\ModuleUpgradeWizardPage;
use Jefferson49\Webtrees\Module\CustomModuleManager\Configuration\ModuleUpdateServiceConfiguration;


/**
 * @var string     $title
 * @var Collection $custom_modules
 * @var Collection $themes
 * @var array      $module_names

 * @var AbstractModuleUpdate $module_update_service
 * @var CustomModuleManager  $module
 */

$module_service = New ModuleService();

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => MoreI18N::xlate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<table
    class="table table-bordered table-sm wt-table-module-updates datatables d-none"
    <?= view('lists/datatables-attributes') ?>
    data-columns="<?= e(json_encode([
        ['type' => 'html'],
        ['type' => 'html'],
        null,
        ['searchable' => false],
        null,
        null,
        null,
        ['searchable' => false],
        ['type' => 'html', 'searchable' => false],
    ], JSON_THROW_ON_ERROR)) ?>"
>
    <caption class="visually-hidden">
        <?= $caption ?? I18N::translate('Module Updates') ?>
    </caption>

    <thead>
        <tr>
            <th><?= MoreI18N::xlate('Title') ?></th>
            <th><?= MoreI18N::xlate('Description') ?></th>
            <th><?= I18N::translate('Folder (within modules_v4)') ?></th>
            <th><?= MoreI18N::xlate('Theme') ?></th>
            <th><?= I18N::translate('Current Version') ?></th>
            <th><?= I18N::translate('Latest Version') ?></th>
            <th><?= I18N::translate('Update Service') ?></th>
            <th><?= MoreI18N::xlate('Status') ?></th>
            <th><?= MoreI18N::xlate('Action') ?></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($module_names as $standard_module_name => $module_name) : ?>
            <?php $module = $module_service->findByName($module_name, true) ?>
            <?php if ($module === null) : ?>
                <?php $module_status = I18N::translate('not installed') ?>
            <?php elseif ($module->isEnabled()) : ?>
                <?php $module_status = I18N::translate('enabled') ?>
            <?php else : ?>
                <?php $module_status = I18N::translate('disabled') ?>
            <?php endif ?>						
            <?php $update_service_available = ModuleUpdateServiceConfiguration::getUpdateServiceName($module_name) !== '' ?>
            <?php if ($update_service_available) : ?>
                <?php $module_update_service = CustomModuleUpdateFactory::make($module_name) ?>
                <?php $module_update_service_name = $module_update_service->name() ?>
                <?php $module_title = $module_update_service->title() ?>
                <?php $module_description = $module_update_service->description() ?>
				<?php $current_version = $module_update_service->customModuleVersion() ?>
				<?php $latest_version = $module_update_service->customModuleLatestVersion() ?>
				<?php $documentation_url = $module_update_service->documentationUrl() ?>
            <?php else : ?>						
                <?php $module_update_service_name = I18N::translate('not available') ?>
                <?php $module_title = $module->title() ?>
                <?php $module_description = $module->description() ?>
                <?php /** @var CustomModuleManager $module To avoid IDE warnings */ ?>
				<?php $current_version = $module->customModuleVersion() ?>
				<?php $latest_version = $module->customModuleLatestVersion() ?>
            <?php endif ?>						

            <tr>
                <!-- Title -->
                <td data-sort="<?= e($module_title) ?>">
                    <?php if ($documentation_url !== '') : ?>
                        <a href="<?= e($documentation_url) ?>" target="blank">
                            <?= e($module_title) ?>
                        </a>
                    <?php else : ?>		
                        <?= e($module_title) ?>		
                    <?php endif ?>						
                </td>

                <!-- Description -->
               <td data-sort="<?= e($module_description) ?>">
                    <?= e($module_description) ?>
                </td>

                <!-- Folder -->
				<?php $installation_folder = $module_update_service::getInstallationFolderFromModuleName($module_name) ?>
                <td data-sort="<?= e($installation_folder) ?>">
					<?= e($installation_folder) ?>
                </td>

                <!-- Is theme? -->
				<?php $is_theme = $themes->contains($module) ?>
                <td class="text-center" data-sort="<?= $is_theme === true ? '1' : '0' ?>">
					<?php if ($is_theme) : ?>
						<?= MoreI18N::xlate('yes') ?>
					<?php endif ?>						
                </td>

                <!-- Current version -->
                <td data-sort="<?= e($current_version) ?>">
                	<?= e($current_version) ?>
                </td>

                <!-- Latest version -->
                <td data-sort="<?= e($latest_version) ?>">
                	<?= e($latest_version) ?>
                </td>

                <!--Update Service -->
                <td class="text-center" data-sort="<?= $module_update_service_name ?>">
                    <?= $module_update_service_name ?>
                </td>

                <!-- Status -->
                <td data-sort="<?= $module_status ?>">
                	<?= $module_status ?>
                </td>

                <!--Action -->
                <?php $action = '' ?>
                <?php $action_label = '' ?>
                <?php if ($module !== null && version_compare($latest_version, $current_version) > 0) : ?>
    				<?php $action = CustomModuleManager::ACTION_UPDATE ?>
    				<?php $action_label = I18N::translate('Update module') ?>
                <?php elseif ($module_status === I18N::translate('not installed')) : ?>
    				<?php $action = CustomModuleManager::ACTION_INSTALL ?>
    				<?php $action_label = I18N::translate('Install module') ?>
                <?php endif ?>						
                <td data-sort="<?= $action_label ?>">
                    <?php if ($action_label !== '' && $update_service_available) : ?>
                        <a href="<?= e(route(ModuleUpgradeWizardPage::class, [
                                'module_name' => $module_name,
                                'action'      => $action,
                            ])) ?>" type="submit" class="btn btn-secondary">
                            <?= $action_label ?>
                        </a>
                    <?php endif ?>						
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
