<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\CustomModuleManager;

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\CustomModuleManager\RequestHandlers\CustomModuleUpdatePage;


/**
 * @var string $title
 * @var bool   $runs_with_webtrees_version
 * @var bool   $php_extension_zip_missing
 * @var string $github_api_token
 * @var string $modules_to_show
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => MoreI18N::xlate('Control panel'), e($title)]]) ?>

<h1><?=e($title) ?></h1>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<?= view(CustomModuleManager::viewsNamespace() . '::deactivated', [
		'runs_with_webtrees_version' => $runs_with_webtrees_version,
		'php_extension_zip_missing'  => $php_extension_zip_missing,
]) ?>
<div class="row mb-3">
	<div class="col">
		<a href="<?= e(route(CustomModuleUpdatePage::class, [
			'modules_to_show' => $modules_to_show,
			'runs_with_webtrees_version' => $runs_with_webtrees_version,
			'php_extension_zip_missing'  => $php_extension_zip_missing,				
		])) ?>" type="submit" class="btn btn-secondary">
			<?= I18N::translate('Manage custom modules') ?>
		</a>
	</div>
</div>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<form method="post" id="settings-form">
	<?= csrf_field() ?>
	<input type="hidden" name="save" id="save" value="1">

	<div class="h4">
		<?= I18N::translate('Settings for List Menu') ?>	
	</div>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Show menu item in list menu') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/checkbox', ['label' => MoreI18N::xlate('Show'), 'name' => CustomModuleManager::PREF_SHOW_MENU_LIST_ITEM, 'checked' => $show_menu_list_item]) ?>
				<div class="form-text">
					<?= I18N::translate('If this option is selected, a link to the page "%s" will be shown as a list menu item.', I18N::translate('Custom Module Updates')); ?>
				</div>
			</div>
		</div>
	</fieldset>

	<div class="h4">
		<?= I18N::translate('Selection of the custom modules to show') ?>	
	</div>

	<div class="row">
		<label class="col-sm-3" for="modules_to_show">
			<?= I18N::translate('Modules to show') ?>
		</label>
		<div class="col-sm-9">
			<div class="form-check">
				<input class="form-check-input" type="radio" name="modules_to_show" id="modules-show-all" value="<?= CustomModuleManager::PREF_SHOW_ALL ?>" <?= $modules_to_show === CustomModuleManager::PREF_SHOW_ALL ? 'checked="checked"' : '' ?>>

				<label class="form-check-label" for="modules-show-all">
					<?= I18N::translate('Show all custom modules') ?>
				</label>
			</div>
			<div class="form-check">
				<input class="form-check-input" type="radio" name="modules_to_show" id="modules-show-installed" value="<?= CustomModuleManager::PREF_SHOW_INSTALLED ?>" <?= $modules_to_show === CustomModuleManager::PREF_SHOW_INSTALLED ? 'checked="checked"' : '' ?>>

				<label class="form-check-label" for="modules-show-installed">
					<?= I18N::translate('Show installed custom modules (in order to update modules)') ?>
				</label>
			</div>
			<div class="form-check">
				<input class="form-check-input" type="radio" name="modules_to_show" id="modules-show-not-installed" value="<?= CustomModuleManager::PREF_SHOW_NOT_INSTALLED ?>" <?= $modules_to_show === CustomModuleManager::PREF_SHOW_NOT_INSTALLED ? 'checked="checked"' : '' ?>>

				<label class="form-check-label" for="modules-show-not-installed">
					<?= I18N::translate('Show not installed custom modules (in order to install new modules)') ?>
				</label>
			</div>
		</div>
	</div>	

	<div class="h4">
		<?= I18N::translate('GitHub API token') ?>	
	</div>
	<p><?= I18N::translate('The custom module makes intensive use of the GitHub API to retrieve module versions and download URLs. However, GitHub limits the frequency of API calls for a certain IP address. In order to significantly increase the allowed frequency of GitHub API calls, GitHub requires to use a GitHub API token.'); ?></p>
	<p><?= I18N::translate('Using a GitHub API token is recommended, if GitHub communication errors occur') ?></p>
	<div class="row">
		<label class="col-sm-3 col-form-label wt-page-options-label" for="new_secret_key">
			<?= I18N::translate('GitHub API token') ?>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<input class="form-control" id="github_api_token" name="github_api_token" type="text" value="<?= e($github_api_token) ?>">
		</div>

	</div>
	<div class="row">
		<div class="col">
			<p></p>
			<button type="submit" class="btn btn-primary">
				<?= view('icons/save') ?>
				<?= MoreI18N::xlate('save') ?>
			</button>
		</div>		
	</div>
</form>	

<?php View::push('javascript') ?>
<script>
    $('#select-all-1').change(function(e) {
        if (e.currentTarget.checked) {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', true);
        } else {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', false);
        }
    });
</script>
<?php View::endpush() ?>