<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\CustomModuleManager;

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Module\ModuleCustomInterface;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\View;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\CustomModuleManager\RequestHandlers\CustomModuleUpdatePage;


/**
 * @var string $activated
 * @var string $title
 * @var string $github_api_token
 */

$module_service = New ModuleService();
$custom_updates = $module_service
	->findByInterface(ModuleCustomInterface::class, true)
	->filter(static fn (ModuleCustomInterface $module): bool => version_compare($module->customModuleLatestVersion(), $module->customModuleVersion()) > 0);

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => MoreI18N::xlate('Control panel'), e($title)]]) ?>

<h1><?=e($title) ?></h1>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<form method="post" id="settings-form">
	<?= csrf_field() ?>
	<input type="hidden" name="save" id="save" value="1">

	<?php if ($activated) : ?>
		<div class="row mb-3">
			<div class="col">	
				<a href="<?= e(route(CustomModuleUpdatePage::class)) ?>" type="submit" class="btn btn-secondary">
					<?= I18N::translate('Manage custom modules') ?>
				</a>
			</div>
		</div>
		<div class="row mb-3"><?= view('icons/spacer') ?></div>
	<?php else  : ?>
		<?= view('components/' . 'alert-danger', [
            'alert' => I18N::translate('This custom module can only be used with webtrees %s', CustomModuleManager::SUPPORTED_WEBTREES_VERSION),
        ]) ?>;
	<?php endif	?>

	<div class="h4">
		<div class="row mb-3">
			<?= I18N::translate('Github API token') ?>	
		</div>
	</div>

	<div class="row mb-3">
		<label class="col-sm-3 col-form-label wt-page-options-label" for="new_secret_key">
			<?= I18N::translate('Github API token') ?>
		</label>
		<div class="col-sm-9 wt-page-options-value">
			<input class="form-control" id="github_api_token" name="github_api_token" type="text" value="<?= e($github_api_token) ?>">
		</div>
	</div>
	<div class="row mb-3">
		<div class="col">
			<p></p>
			<button type="submit" class="btn btn-primary">
				<?= view('icons/save') ?>
				<?= MoreI18N::xlate('save') ?>
			</button>
		</div>		
	</div>
</form>	

<?php View::push('javascript') ?>
<script>
    $('#select-all-1').change(function(e) {
        if (e.currentTarget.checked) {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', true);
        } else {
            $('.mb-3 .row').find('input[type="checkbox"]').prop('checked', false);
        }
    });
</script>
<?php View::endpush() ?>