<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\CustomModuleManager;

use Fisharebest\Webtrees\View;
use Jefferson49\Webtrees\Internationalization\MoreI18N;


/**
 * @var array<string,string> $steps
 * @var string               $title
 */

?>

<?php if ($title !== '') : ?>
    <h3>
        <?= $title ?>
    </h3>
<?php endif ?>

<p>
    <?= MoreI18N::xlate('It can take several minutes to download and install the upgrade. Be patient.') ?>
</p>

<dl>
    <?php foreach ($steps as $url => $text) : ?>
    <dt><?= $text ?></dt>
    <dd class="wt-ajax-load" data-url="<?= e($url) ?>"></dd>
    <?php endforeach ?>
</dl>

<?php View::push('javascript') ?>
<script>
  function nextAjaxStep() {
    $("dd:empty:first").each(function(n, el) {
      $(el).load(el.dataset.url, {}, function (responseText, textStatus, req) {
        el.innerHTML = responseText;
        if (textStatus === "error") {
          $(".wt-ajax-load").removeClass("wt-ajax-load");
        } else {
          nextAjaxStep();
        }
      });

      // Only process one callback at a time.
      return false;
    });
  }

  nextAjaxStep();
</script>
<?php View::endpush() ?>
